development:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_development
  host: 104.236.83.32
  username: ntpumis
  password: ntpumis2015

production:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: ntpumis2015.ddns.net
  username: ntpumis
  password: ntpumis2015
