development:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: 104.236.83.32
  username: root
  password: 1qaz2wsx

test:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_test
  host: 104.236.83.32
  username: root
  password: 1qaz2wsx

production:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: 104.236.83.32
  username: root
  password: 1qaz2wsx
