# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eab9967e935a4633bf1f2ddd9c8ca8ba5cd1310122ca94149614d614bea7f8550ae9f87d644b49d6892f8edd24a6c2aa946043b95445b6a87c2816394a2995e9

test:
  secret_key_base: 2c864ef570cc225fbd283201b6897ad62d4aeacc649ff3e686d74f959e3671625a9bb0638397cd8aa77647d19c77ea7a56d92cb686b4ace57967ec57f085c0ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: eab9967e935a4633bf1f2ddd9c8ca8ba5cd1310122ca94149614d614bea7f8550ae9f87d644b49d6892f8edd24a6c2aa946043b95445b6a87c2816394a2995e9
